[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'elzr/vim-json'
